<h4>Arrays in Numpy</h4>

<h5>Normal lists vs Numpy arrays</h5>

Normal python list are in python and numpy arrays are built in C. Hence faster

In [1]:
import numpy as np

<strong>1. One dimensional array</strong>

In [ ]:
my_list = [1, 2, 3]
my_np_list = np.array([1,2,3])

# print(my_np_list)
print(type(my_np_list))

<class 'numpy.ndarray'>


<strong>2. Two dimensional array</strong>

In [19]:
array = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]], [[13,14,15], [16,17,18]]])

print(array)
print(array.ndim)
print(array.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
3
(3, 2, 3)


<p>Indexing in nD array</p>

In [20]:
# chain indexing
print(array[0][1][1])

# multidimension indexing
print(array[0, 1, 1])

print(array)

5
5
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


<strong>2. Slicing</strong>

In [29]:
# print(array[0:3:2]) 

# print(array[0:2, 0:1, 0:2])


print(array[0::2, :, ::2])

[[[ 1  3]
  [ 4  6]]

 [[13 15]
  [16 18]]]


<strong>3. Operations</strong>

a. vector arithimatic operations

In [30]:
arr = np.array([1,2,3])

arr*2

array([2, 4, 6])

b. vector functions

In [34]:
print(np.sqrt(arr))
print(np.round(arr))
print(np.mean(arr))
print(np.pi)

[1.         1.41421356 1.73205081]
[1 2 3]
2.0
3.141592653589793


c. Element-wise operations

In [37]:
# print(arr*2)
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])

print(arr1 + arr2)

[2 4 6]


d. Comparison operations

In [40]:
print(arr > 2)

[False False  True]


e. Broadcasting <br />
f. aggregation functions

<strong>4. Filtering</strong>

In [52]:
ages = np.array([13, 45, 24, 34, 36 ,12, 4, 23, 17, 18])

teens = ages[(ages <= 18) & (ages >= 12)]
print(teens)

[13 12 17 18]


<strong>5. Random number generator</strong>

In [ ]:
rng = np.random.default_rng()
arr4 = np.array([1,2,3,4,5])
# print(rng.integers(low=10, high=20, size=(5,5)))
rng.shuffle(arr4)
# print(rng.choice(arr4))
# print(rng.choice(arr4, size=(2,2)))
# print(arr4)

[[1 1]
 [2 1]]
